[default.extend-words]


[files]
extend-exclude = [
    "CHANGELOG.md",
    "notebooks/*",
    "config/development.yaml",
    "migration",
    "fixtures/*",
]

[default.extend-identifiers]
vuln_informations = "vuln_informations"
VulnInformations = "VulnInformations"
