//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "vuln_informations")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub key: String,
    pub title: String,
    pub description: String,
    pub severtiy: String,
    pub cve: String,
    pub disclosure: String,
    pub solutions: String,
    pub references: Option<Vec<String>>,
    pub tags: Option<Vec<String>>,
    pub github_search: Option<Vec<String>>,
    pub reasons: Option<Vec<String>>,
    pub from: String,
    pub pushed: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
