version: "3"
services:
  app:
    restart: always
    image: fantasticzf/watchvuln-rs:latest
    env_file:
      - env/app.env
    volumes:
      - "./config:/app/config"
    networks:
      - vuln
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    # ports:
    #   - 5432:5432
    networks:
      - vuln
    volumes:
      - "./data:/var/lib/postgresql/data"
    env_file:
      - env/postgres.env
